---
- name: Install nginx on the nodes
  hosts: nodes
  become: yes

  tasks:
  - name: nginx for Any Linux
    include_tasks: "{{ lnx_name }}.yml"

  handlers:
  - name: Restart nginx web server
    service: name=nginx state=restarted